SELECT OBJECT_ID, [NAME], [TYPE], SCHEMA_NAME(SCHEMA_ID) [SCHEMA_NAME], [TYPE_DESC], CREATE_DATE, MODIFY_DATE
FROM SYS.OBJECTS
WHERE [NAME] LIKE '%COUNTLOGINS%'


SELECT OBJECT_ID, [NAME], [TYPE], SCHEMA_NAME(SCHEMA_ID) [SCHEMA_NAME], [TYPE_DESC], CREATE_DATE, MODIFY_DATE
  FROM SYS.OBJECTS
 WHERE [NAME] LIKE '%period%'
   AND [TYPE] = 'P'
ORDER BY [NAME] ASC

SELECT OBJECT_ID, [NAME], [TYPE], SCHEMA_NAME(SCHEMA_ID) [SCHEMA_NAME], [TYPE_DESC],'SELECT TOP (10) * FROM '+SCHEMA_NAME(SCHEMA_ID)+'.'+[NAME] [SELECT]
FROM SYS.OBJECTS
WHERE [NAME] LIKE '%%'
  AND [TYPE] = 'U'
