SELECT OBJECT_ID, [NAME], [TYPE], SCHEMA_NAME(SCHEMA_ID) [SCHEMA_NAME], [TYPE_DESC], CREATE_DATE, MODIFY_DATE
FROM SYS.OBJECTS
WHERE [NAME] LIKE '%COUNTLOGINS%'


SELECT OBJECT_ID, [NAME], [TYPE], SCHEMA_NAME(SCHEMA_ID) [SCHEMA_NAME], [TYPE_DESC], CREATE_DATE, MODIFY_DATE
FROM SYS.OBJECTS
WHERE [NAME] LIKE '%COUNTLOGINS%'
  AND [TYPE] = 'P'