IF EXISTS (SELECT 1 
             FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = 'dbo' 
              AND TABLE_NAME = 'TB_PURCHASEFINAL')
BEGIN
    SELECT TOP 25 * 
      FROM DBO.TB_PURCHASEFINAL
END
ELSE
BEGIN
    PRINT 'Table DBO.TB_PURCHASEFINAL does not exist.'
END